import type { CouponTemplate } from "./coupons.js";

/** 活动配置引用的默认可券模板（缺失时自动补建） */
export const COUPON_TEMPLATE_DEFAULTS: CouponTemplate[] = [
  {
    id: "cp_welcome",
    name: "新人满减券",
    description: "注册后可领取，首单可用",
    type: "fixed",
    value: 10,
    minSpend: 50,
    maxDiscount: 0,
    validDays: 30,
    scope: "all",
    enabled: true,
    sortOrder: 1,
  },
  {
    id: "cp_invite_inviter",
    name: "邀请人奖励券",
    description: "好友完成首单后，邀请人获得",
    type: "fixed",
    value: 15,
    minSpend: 0,
    maxDiscount: 0,
    validDays: 30,
    scope: "all",
    enabled: true,
    sortOrder: 4,
  },
  {
    id: "cp_invite_invitee",
    name: "被邀请人奖励券",
    description: "通过邀请注册并完成首单后获得",
    type: "fixed",
    value: 10,
    minSpend: 0,
    maxDiscount: 0,
    validDays: 30,
    scope: "all",
    enabled: true,
    sortOrder: 5,
  },
  {
    id: "cp_vip_escort",
    name: "VIP 护航券",
    description: "VIP 会员护航订单可用",
    type: "fixed",
    value: 20,
    minSpend: 100,
    maxDiscount: 0,
    validDays: 7,
    scope: "escort",
    enabled: true,
    sortOrder: 2,
  },
  {
    id: "cp_discount_95",
    name: "全场 95 折券",
    description: "限时折扣，最高减 50 元",
    type: "percent",
    value: 9.5,
    minSpend: 80,
    maxDiscount: 50,
    validDays: 14,
    scope: "all",
    enabled: true,
    sortOrder: 3,
  },
];

export const COUPON_TEMPLATE_BY_ID = Object.fromEntries(
  COUPON_TEMPLATE_DEFAULTS.map((item) => [item.id, item]),
) as Record<string, CouponTemplate>;
