export {
  ADMIN_ROLE_DESCRIPTIONS,
  ADMIN_ROLE_LABELS,
  ADMIN_ROLES,
  DEFAULT_ROLE_PERMISSIONS,
  EDITABLE_ROLES,
  PERMISSION_GROUPS,
  PERMISSION_LABELS,
  avatarInitial,
  isEditableRole,
  isServiceProviderRole,
  permissionLabel,
  permissionsEqual,
  roleLabels,
  type AdminPermission,
  type AdminRole,
} from "@meme/admin-rbac";
